const express = require('express')
const app = express()
const cors = require('cors')
const PORT = 8000

app.use(cors())
app.use(express.static(__dirname + '/public'));


app.listen(process.env.PORT || PORT, () => {
    console.log(`The server is now running on port ${PORT}`)
})

app.get('/', (req, res) => {
    res.sendFile(__dirname + '/index.html')
})

app.get('/api', (req, res) => {
    res.json(caseload);
})

app.get('/api/:name', (req, res) => {
    let particName = req.params.name.toLowerCase()
    res.json(caseload[particName])
})


const caseload = {
    'bijou mbenga': {
        'name': 'Bijou Mbenga',
        'mask': 'V270043560',
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'brandon hodges': {
        'name': 'Brandon Hodges',
        'mask': 'N23434357',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'n/a',
        'status': 'Termed',
        'Term Date': 0,
    },
    'craig kidwell': {
        'name': 'Craig Kidwell',
        'mask': 'C85904357',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'frida valdez': {
        'name': 'Frida Valdez',
        'mask': 'D56610202',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'n/a',
        'status': 'Termed',
        'Term Date': 0,
    },
    'ladaydrea king': {
        'name': 'LaDayDrea King',
        'mask': 'N37415368',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'malak khatib': {
        'name': 'Malak Khatib',
        'mask': 'F03175366',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'patrick song': {
        'name': 'Patrick Song',
        'mask': 'C79435355',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'completed',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'reece hayden': {
        'name': 'Reece Hayden',
        'mask': 'C65574358',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 54,
    },
    'thomas whalen': {
        'name': 'Thomas Whalen',
        'mask': 'X90016462',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'zachery hennigan': {
        'name': 'Zachary Hennigan',
        'mask': 'H23722351',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 54,
    },
    'ian roynak': {
        'name': 'Ian Roynak',
        'mask': 'X96169329',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'everett roynak': {
        'name': 'Everett Roynak',
        'mask': 'X86179329',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'ashley villa': {
        'name': 'Ashley Villa',
        'mask': 'N98418331',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'adan harun': {
        'name': 'Adan Harun',
        'mask': 'D51675103',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'carissa barrett': {
        'name': 'Carissa Barrett',
        'mask': 'Y93354358',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'chevon underwood': {
        'name': 'Chevon Underwood',
        'mask': 'G34282359',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'deisy rosales': {
        'name': 'Deisy Rosales',
        'mask': 'C77781234',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'elijah trujillo': {
        'name': 'Elijah Trujillo',
        'mask': 'G34282359',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'hawa roble': {
        'name': 'Hawa Roble',
        'mask': 'N41814359',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'isaiah mccormick': {
        'name': 'Isaiah McCormick',
        'mask': 'C42666628',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'jaila marquez': {
        'name': 'Jaila Marquez',
        'mask': 'V69404359',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'james beatty': {
        'name': 'James Beatty',
        'mask': 'F08914557',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'jaylah short': {
        'name': 'Jaylah Short',
        'mask': 'R83284357',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'jennifer salgado': {
        'name': 'Jennifer Salgado',
        'mask': 'N14879325',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'kyle ford': {
        'name': 'Kyle Ford',
        'mask': 'G73771888',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Thrive Tutoring',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'nelson alvarado': {
        'name': 'Nelson Alvarado',
        'mask': 'G06064755',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'suhaila farahi': {
        'name': 'Suhaila Farahi',
        'mask': 'V86637358',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'sunita sangraula': {
        'name': 'Sunita Sangraula',
        'mask': 'D84627257',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'zola saulsberry': {
        'name': 'Zola Saulsberry',
        'mask': 'G27625367',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'jozef jones': {
        'name': 'Jozef Jones',
        'mask': 'X27975366',
        'age' : 20,
        'programs': 'Young Adult In, ARPA',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'shemaiah holiway': {
        'name': 'Shemaiah Holiway',
        'mask': 'H39016367',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'angel castillo': {
        'name': 'Angel Castillo',
        'mask': 'G15815355',
        'age' : 20,
        'programs': 'Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'aihaim khudhair': {
        'name': 'Aiham Khudhair',
        'mask': 'V85803227',
        'age' : 20,
        'programs': 'Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'gela glover': {
        'name': 'Gela Glover',
        'mask': 'H69959640',
        'age' : 20,
        'programs': 'Adult',
        'trainings': 'Medical Billing and Coding',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'lloytisha moore': {
        'name': 'Lloytisha Moore',
        'mask': 'N99904685',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'calum hart': {
        'name': 'Calum Hart',
        'mask': 'H85095368',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'kenwyn kamara': {
        'name': 'Kenwyn Kamara',
        'mask': 'X57043358',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'alena ford': {
        'name': 'Alena Ford',
        'mask': 'C05096364',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Thrive Tutoring',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'thyeba aman': {
        'name': 'Theyba Aman',
        'mask': 'Y47947155',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'VWR',
        'ged': 'Self-Study',
        'supportiveServices': 'Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'victor bradley': {
        'name': 'Victor Bradley',
        'mask': 'R78451372',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'jaden banks': {
        'name': 'Jaden Banks',
        'mask': 'D42132435',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'completed',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'maya speegle': {
        'name': 'Maya Speegle',
        'mask': 'F68069318',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'isabel york': {
        'name': 'Isabel York',
        'mask': 'Y47947155',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Thrive Tutoring',
        'supportiveServices': 'Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'marley hadden': {
        'name': 'Marley Hadden',
        'mask': 'V19035370',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'alexander broxton': {
        'name': 'Alexander Broxton',
        'mask': 'R88232434',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'matthew mccoy': {
        'name': 'Matthew McCoy',
        'mask': 'F7732360',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'riyana anderson': {
        'name': 'Riyana Anderson',
        'mask': 'C43873358',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'Graphic Design',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'savanna burkham': {
        'name': 'Savanna Burkham',
        'mask': 'V59785368',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'alejandro chavez': {
        'name': 'Alejandro Chavez',
        'mask': 'C07175366',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'kaycee hannifan': {
        'name': 'Kaycee Hannifan',
        'mask': 'Y90368400',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'CDL',
        'ged': 'Self-Study',
        'supportiveServices': `Gas Vouchers, Rent, Other`,
        'status': 'Active',
        'Term Date': 0,
    },
    'sam houghton': {
        'name': 'Sam Houghton',
        'mask': 'R69124357',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'john houghton': {
        'name': 'John Houghton',
        'mask': 'V03396369',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Termed',
        'Term Date': 0,
    },
    'allan fuhlhage': {
        'name': 'Allan Fuhlhage',
        'mask': 'H5679S1',
        'age' : 19,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': `Thrive Tutoring [March: $2300, April: $1200]`,
        'supportiveServices': 'GED Tests'
    },
    'anthony marshall': {
        'name': 'Anthony Marshall',
        'mask': 'H65655367',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'laquan bowie': {
        'name': 'Laquan Bowie',
        'mask': 'F67544357',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'caleb medina': {
        'name': 'Caleb Medina',
        'mask': 'X16009331',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'isaiah arias': {
        'name': 'Isaiah Arias',
        'mask': 'R86521487',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Termed',
        'Term Date': 0,
    },
    'aliza guerrero': {
        'name': 'Aliza Guerrero',
        'mask': 'G99085368',
        'age' : 20,
        'programs': 'Young Adult In',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'ryan fullenwinder': {
        'name': 'Ryan Fullenwinder',
        'mask': 'R78466462',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'nathan le': {
        'name': 'Nathan Le',
        'mask': 'R43514358',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'derek hamlin': {
        'name': 'Derek Hamlin',
        'mask': 'Y07654358',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'racsmey saesee': {
        'name': 'Racsmey Saesee',
        'mask': 'N51264356',
        'age' : 21,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Negative Term',
        'Term Date': 0,
    },
    'sara richey': {
        'name': 'Sara Richey',
        'mask': 'N97675368',
        'age' : 23,
        'programs': 'Young Adult Out',
        'trainings': 'GED Prep Course at ACC',
        'ged': `Thrive Tutoring [May: $500, June: $900]`,
        'supportiveServices': 'Thrive Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'fabiola nevarez': {
        'name': 'Fabiola Nevarez',
        'mask': 'N97675368',
        'age' : 17,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': `Thrive Tutoring [March: $262.50, April: $300, May: $543.75]`,
        'supportiveServices': 'Thrive Tutoring Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'malika isaac': {
        'name': 'Malika Isaac',
        'mask': 'C71144359',
        'age' : 18,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Negative Term',
        'Term Date': 0,
    },
    'ahlaysha sipes': {
        'name': 'Ahlaysha Sipes',
        'mask': 'N31153358',
        'age' : 20,
        'programs': 'Young Adult In, Adult, Colorado Works',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Negative Term',
        'Term Date': 0,
    },
    'chardonnay jones': {
        'name': 'Chardonnay Jones',
        'mask': 'D23635325',
        'age' : 24,
        'programs': 'Young Adult Out, Adult, Colorado Works',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Negative Term',
        'Term Date': 0,
    },
    'noah buckley': {
        'name': 'Noah Buckley',
        'mask': 'G39925366',
        'age' : 18,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': `Thrive Tutoring [March: $900, April: $900, May: $150], Self-Study`,
        'supportiveServices': 'Thrive Tutoring Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'kyle souther': {
        'name': 'Kyle Souther',
        'mask': 'F01821354',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'Gas Vouchers, Phone Bill',
        'status': 'Active',
        'Term Date': 0,
    },
    'evan gudmunson': {
        'name': 'Evan Gudmunson',
        'mask': 'R29545368',
        'age' : 18,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'GED Prep Book',
        'status': 'Active',
        'Term Date': 0,
    },
    'brady jones': {
        'name': 'Brady Jones',
        'mask': 'R93394357',
        'age' : 19,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'ladyasha wolford': {
        'name': 'Ladyasha Wolford',
        'mask': 'D27586369',
        'age' : 20,
        'programs': 'Young Adult In, ARPA',
        'trainings': 'Pharmacy Tech Internsip Program',
        'ged': 'n/a',
        'supportiveServices': `Bus Pass, Gas Vouchers, Driving Classes, Chromebook, Rent Assistance`,
        'status': 'Active',
        'Term Date': 0,
    },
    'kidus zelalem': {
        'name': 'Kidus Zelalem',
        'mask': 'V69205368',
        'age' : 21,
        'programs': 'Young Adult Out, ARPA',
        'trainings': 'Full Stack Boot Camp',
        'ged': 'n/a',
        'supportiveServices': 'Computer Equipment',
        'status': 'Active',
        'Term Date': 0,
    },
    'benjamin mccoy': {
        'name': 'Benjamin McCoy',
        'mask': 'X01054357',
        'age' : 19,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': `Thrive Tutoring [March: $75, April: $75]`,
        'supportiveServices': 'Thrive Tutoring Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'arlette munoz': {
        'name': 'Arlette Munoz',
        'mask': 'Y41735366',
        'age' : 16,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': `Thrive Tutoring [May: $600, June: $225]`,
        'supportiveServices': `Gas Vouchers, Car Payment`,
        'status': 'Active',
        'Term Date': 0,
    },
    'morgan woehler': {
        'name': 'Morgan Woehler',
        'mask': 'H51285751',
        'age' : 19,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Negative Term',
        'Term Date': 0,
    },
    'juan vega ortiz': {
        'name': 'Juan Vega Ortiz',
        'mask': 'N92705146',
        'age' : 20,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'CDL',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'jp simmons': {
        'name': 'JP Simmons',
        'mask': 'F48946476',
        'age' : 20,
        'programs': 'Young Adult Out, Adult, DVR',
        'trainings': 'Graphic Design',
        'ged': 'n/s',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'devin st. laurent': {
        'name': 'Devin St. Laurent',
        'mask': 'F58625487',
        'age' : 24,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'Graphic Design',
        'ged': 'n/a',
        'supportiveServices': 'Car Insurance',
        'status': 'Active',
        'Term Date': 0,
    },
    'makenzie james': {
        'name': 'MaKenzie James',
        'mask': 'Y13120386',
        'age' : 20,
        'programs': 'Young Adult In, ARPA',
        'trainings': 'Medical Assistant',
        'ged': 'n/a',
        'supportiveServices': 'PIMA Medical Supplies, Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'henry ayers': {
        'name': 'Henry Ayers',
        'mask': 'X38741527',
        'age' : 19,
        'programs': 'Young Adult In, Adult',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'faiso shekhow': {
        'name': 'Faiso Shekhow',
        'mask': 'R81053358',
        'age' : 24,
        'programs': 'Young Adult Out',
        'trainings': 'CNA',
        'ged': 'n/a',
        'supportiveServices': 'Car Repo, CNA Supplies, Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'naia stonebraker': {
        'name': 'Naia Stonebraker',
        'mask': 'D58033722',
        'age' : 17,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': 'Thrive Tutoring [June: $75]',
        'supportiveServices': 'Thrive Tutoring Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'gaberial tyndall': {
        'name': 'Gaberial Tyndall',
        'mask': 'G18173441',
        'age' : 16,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': 'Thrive Tutoring [June: $225]',
        'supportiveServices': 'Thrive Tutoring Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'markie fisher': {
        'name': 'Markie Fisher',
        'mask': 'D42634423',
        'age' : 17,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': `completed, Thrive Tutoring [May: $1,050, June: $862.50]`,
        'supportiveServices': 'GED Tests',
        'status': 'Active',
        'Term Date': 0,
    },
    'naimo shekhow': {
        'name': 'Naimo Shekhow',
        'mask': 'N51653358',
        'age' : 22,
        'programs': 'Young Adult Out, Adult, RUN',
        'trainings': 'CNA',
        'ged': 'n/a',
        'supportiveServices': 'Rent Assistance',
        'status': 'Active',
        'Term Date': 0,
    },
    'tailor hill': {
        'name': 'Tailor Hill',
        'mask': 'G93483359',
        'age' : 21,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'maria mendoza': {
        'name': 'Maria Mendoza',
        'mask': 'G01256249',
        'age' : 18,
        'programs': 'Young Adult Out, Adult',
        'trainings': 'n/a',
        'ged': 'Self-Study',
        'supportiveServices': 'GED Prep Book',
        'status': 'Active',
        'Term Date': 0,
    },
    'elaias lucero': {
        'name': 'Elaias Lucero',
        'mask': 'X77805368',
        'age' : 17,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': 'Thrive Tutoring',
        'supportiveServices': 'Thrive Tutoring Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'caleb lucero': {
        'name': 'Caleb Lucero',
        'mask': 'N61555355',
        'age' : 19,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': 'Thrive Tutoring',
        'supportiveServices': 'Thrive Tutoring Onboarding Fee',
        'status': 'Active',
        'Term Date': 0,
    },
    'alexander hunter': {
        'name': 'Alexander Hunter',
        'age' : 24,
        'programs': 'Young Adult Out',
        'trainings': 'n/a',
        'ged': 'Self-study',
        'supportiveServices': 'GED Tests',
        'status': 'Active',
        'Term Date': 0,
    },
    'emily brown': {
        'name': 'Emily Brown',
        'age' : 16,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC. Bus Pass',
        'status': 'Active',
        'Term Date': 0,
    },
    'elizabeth leone': {
        'name': 'Elizabeth Leone',
        'age' : 16,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'ashley remigio': {
        'name': 'Ashley Remigio',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'genesis wolford': {
        'name': 'Genesis Wolford',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC, Gas Vouchers, Chromebook, Rent Assistance',
        'status': 'Active',
        'Term Date': 0,
    },
    'rayyan muzak': {
        'name': 'Rayyan Muzak',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC, Gas Vouchers, Chromebook, Rent Assistance',
        'status': 'Negative Term',
        'Term Date': 0,
    },
    'noelia placensia': {
        'name': 'Noelia Placensia',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'alexander searfoss': {
        'name': 'Alexander Searfoss',
        'age' : 16,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'jennah hassan': {
        'name': 'Jennah Hassan',
        'age' : 16,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'ilana fishman': {
        'name': 'Ilana Fishman',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'catelynn upchurch': {
        'name': 'Catelynn Upchurch',
        'age' : 16,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'zuhra akbar': {
        'name': 'Zuhra Akbar',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'adrian arjona': {
        'name': 'Adrian Arjona',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'aliyah jackson': {
        'name': 'Aliyah Jackson',
        'age' : 18,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'solomon howard': {
        'name': 'Solomon Howard',
        'age' : 18,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Negative Term',
        'Term Date': 0,
    },
    'caley hancock': {
        'name': 'Caley Hancock',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'michael barnes': {
        'name': 'Michael Barnes',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'jada matthews': {
        'name': 'Jada Matthews',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC, Gas Vouchers, Chromebook',
        'status': 'Active',
        'Term Date': 0,
    },
    'skyler welch': {
        'name': 'Skyler Welch',
        'age' : 16,
        'programs': 'Young Adult In, Employment First',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'hannah riley': {
        'name': 'Hannah Riley',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC, Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'devin cartharn': {
        'name': 'Devin Cartharn',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'yaneli aguilar': {
        'name': 'Yaneli Aguilar',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'victoria ruesta': {
        'name': 'Victoria Ruesta',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'alexander buchanan': {
        'name': 'Alexander Buchanan',
        'age' : 17,
        'programs': 'Young Adult In',
        'trainings': 'CCIC',
        'ged': 'n/a',
        'supportiveServices': 'CCIC',
        'status': 'Active',
        'Term Date': 0,
    },
    'jasmine rosenbaum': {
        'name': 'Jasmine Rosenbaum',
        'age' : 24,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'derrick maese': {
        'name': 'Derrick Maese',
        'age' : 22,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'morgan davis': {
        'name': 'Morgan Davis',
        'age' : 20,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'chris jaimez': {
        'name': 'Chris Jaimez',
        'age' : 23,
        'programs': 'Young Adult Out',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'abrahan mota': {
        'name': 'Abrahan Mota',
        'age' : 25,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'bhawana acharya': {
        'name': 'Bhawana Acharya',
        'age' : 23,
        'programs': 'Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'Rent Assistance',
        'status': 'Active',
        'Term Date': 0,
    },
    'raven upchurch': {
        'name': 'Raven Upchurch',
        'age' : 21,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'isaiah tanner': {
        'name': 'Isaiah Tanner',
        'age' : 24,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'Rent Assistance',
        'status': 'Active',
        'Term Date': 0,
    },
    'genesis oats': {
        'name': 'Genesis Oats',
        'age' : 22,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'n/a',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'thomas genereux': {
        'name': 'Thomas Genereux',
        'age' : 24,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'faduma ahmed': {
        'name': 'Faduma Ahmed',
        'age' : 25,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'tristan hayes': {
        'name': 'Tristan Hayes',
        'age' : 21,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'alexa renteria': {
        'name': 'Alexa Renteria',
        'age' : 23,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'HPI Notebook',
        'status': 'Active',
        'Term Date': 0,
    },
    'daniel guerrero-ramos': {
        'name': 'Daniel Guerrero-Ramos',
        'age' : 22,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'bakhtovar saydaliev': {
        'name': 'bakhtovar saydaliev',
        'age' : 24,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'molly johnston': {
        'name': 'Molly Johnston',
        'age' : 24,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'Clothing',
        'status': 'Active',
        'Term Date': 0,
    },
    'yadira venegas': {
        'name': 'Yadira Venegas',
        'age' : 21,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'jasmine rosenbaum': {
        'name': 'Jasmine Rosenbaum',
        'age' : 24,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'valerie boffa': {
        'name': 'Valerie Boffa',
        'age' : 23,
        'programs': 'RUN',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'n/a',
        'status': 'Active',
        'Term Date': 0,
    },
    'dominic garcia': {
        'name': 'Dominic Garcia',
        'age' : 24,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'Car Payment, Gas Vouchers',
        'status': 'Active',
        'Term Date': 0,
    },
    'ealaff moutaoufik': {
        'name': 'Ealaff Moutaoufik',
        'age' : 19,
        'programs': 'Young Adult Out, Tec-P',
        'trainings': 'COMPTIA',
        'ged': 'n/a',
        'supportiveServices': 'Driving Classes',
        'status': 'Active',
        'Term Date': 0,
    }
}